#!/bin/bash

# Prevent for loops from splitting filenames containing whitespace
IFS="
"

declare -A SUBTOTAL

add() {
    : $((SUBTOTAL[$1] += $2))
}

count() {
    case $1 in
        ruby)       add $1 $(ruby_count $2);;
        awk|shell)  add $1 $(generic_count $2);;
        c|css)      add $1 $(stripcmt $2 | basic_count);;
    esac
}

detect() {
    case $(head -1 $1) in
        \#!*/awk*)  count awk $1;;
        \#!*/ruby*) count ruby $1;;
        \#!*/??sh*) count shell $1;;
    esac
}

for FILE in $(find "$PWD" -type f -not -path "$PWD/.*"); do
    case $FILE in
        *.awk) count awk $FILE;;
        *.rb)  count ruby $FILE;;
        *.c)   count c $FILE;;
        *.css) count css $FILE;;
        *)     detect $FILE;;
    esac
done

for KEY in ${!SUBTOTAL[@]}; do
    printf "%-8s %d\n" $KEY: ${SUBTOTAL[$KEY]}
    : $((TOTAL += ${SUBTOTAL[$KEY]}))
done

printf "%-8s %d\n" total: $TOTAL
