#!/bin/bash

# Prevent for loops from splitting filenames containing whitespace
IFS="
"

declare -A SUBTOTAL

count() {
    : $((SUBTOTAL[$1] += $(./$1_count $2)))
}

detect() {
    case $(head -1 $1) in
        \#!*/awk*)  count awk $1;;
        \#!*/ruby*) count ruby $1;;
    esac
}

for FILE in $(find "$PWD" -type f -not -path "$PWD/.*"); do
    case $FILE in
        *.awk) count awk $FILE;;
        *.rb)  count ruby $FILE;;
        *)     detect $FILE;;
    esac
done

for KEY in ${!SUBTOTAL[@]}; do
    printf "%-8s %d\n" $KEY: ${SUBTOTAL[$KEY]}
    : $((TOTAL += ${SUBTOTAL[$KEY]}))
done

printf "%-8s %d\n" total: $TOTAL
